### PR TITLE
NIFI-7906 Fixed a bug in how record paths were handled.

### PR DESCRIPTION
**Pull request by MikeThomsen**
Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by MikeThomsen** [comment]
Here's the flow: [Updated_Graph_Test.xml.txt](https://github.com/mattyb149/nifi/files/5638869/Updated_Graph_Test.xml.txt)

**Comment by MikeThomsen** [comment]
Gremlin setup:

```
         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/janusgraph/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/janusgraph/lib/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
plugin activated: tinkerpop.server
plugin activated: tinkerpop.tinkergraph
19:44:41 WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
plugin activated: tinkerpop.hadoop
plugin activated: tinkerpop.spark
plugin activated: tinkerpop.utilities
plugin activated: janusgraph.imports
gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Configured localhost/127.0.0.1:8182
gremlin> 
gremlin> 
gremlin> :> g.V("person").property("name", "John").property("age", 35).next()
java.util.NoSuchElementException
Type ':help' or ':h' for help.
Display stack trace? [yN]
gremlin> 
gremlin> :> g.addV("person").property("name", "John").property("age", 35).next()
==>v[4304]
gremlin> 
gremlin> 
gremlin> :> g.V().hasLabel("person").has("name", eq("John")).valueMap().next()
==>name=[John]
==>age=[35]
gremlin> 
```

Cypher setup:

```
CREATE (n:Person { name: 'Andy', title: 'Developer' })
CREATE (n:Person { name: 'John' })
```

JanusGraph setup:

```
docker run --name janusgraph -p 8182:8182 -d janusgraph/janusgraph:latest
```

Neo4J setup:

```
docker run --name neo4j -p 7474:7474 -p 7687:7687 -d neo4j:3.5
```

**Comment by MikeThomsen** [comment]
Screen Shot 2020-12-03 at 4 01 01 PM
Screen Shot 2020-12-03 at 4 00 26 PM
Screen Shot 2020-12-03 at 3 59 26 PM

Screen Shot 2020-12-03 at 3 59 02 PM

**Comment by mattyb149** [comment]
Looks like there are test failures

**Comment by MikeThomsen** [comment]
Yup. Don't know how I missed that other than "it's been one of a last two weeks."

**Comment by MikeThomsen** [comment]
@levilentz please jump in and review the changes I made.

**Comment by levilentz** [comment]
@MikeThomsen, just took a look at the code, and that is a very nice way to fix the issues associated with the original code.  Apologies to you and @mattyb149 for introducing this bug.

**Pull request closed without merging**
